version: '3.8'

services:
  symfony:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony-app
    ports:
      - "8000:8000"
    volumes:
      - ./application:/var/www/symfony
    networks:
      - symfony_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  mysql_data:

networks:
  symfony_network:
    driver: bridge
