<?php

namespace ContainerVEz0Yfx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeatherServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\WeatherService' shared autowired service.
     *
     * @return \App\Service\WeatherService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/WeatherService.php';

        return $container->privates['App\\Service\\WeatherService'] = new \App\Service\WeatherService($container->getEnv('WEATHER_API_KEY'), ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
