<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'weather_index' => [[], ['_controller' => 'App\\Controller\\WeatherController::index'], [], [['text', '/']], [], [], []],
    'weather_show' => [[], ['_controller' => 'App\\Controller\\WeatherController::show'], [], [['text', '/weather']], [], [], []],
    'App\Controller\WeatherController::index' => [[], ['_controller' => 'App\\Controller\\WeatherController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\WeatherController::show' => [[], ['_controller' => 'App\\Controller\\WeatherController::show'], [], [['text', '/weather']], [], [], []],
];
